name: Docker deployment

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the image for testing
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/engine.Dockerfile
          load: true
          tags: asreview/asreview-engine:test
      - name: Test the built image
        run: |
          docker run asreview/asreview-engine:test -h

      - name: Docker meta
        id: meta
        if: github.event_name != 'pull_request'
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/asreview/asreview-engine
      - name: Login to GitHub registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and, if it is not a pull request, push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/engine.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Docker meta for asreview lab, if this is a tag
        id: meta-lab
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/asreview/asreview
      - name: Build and deploy asreview lab, if this is a tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/lab.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-lab.outputs.tags }}
          labels: ${{ steps.meta-lab.outputs.labels }}

      - name: Docker meta for asreview cli, if this is a tag
        id: meta-cli
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/asreview/asreview-cli
      - name: Build and deploy asreview cli, if this is a tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/cli.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-cli.outputs.tags }}
          labels: ${{ steps.meta-cli.outputs.labels }}
